In [2]:
import numpy as np
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [3]:
x[0]

1

In [5]:
x[5]

6

In [7]:
# slicing
x[:4]

array([1, 2, 3, 4])

In [8]:
np.save('x', x)

In [9]:
np.load('x.npy')

array([1, 2, 3, 4, 5, 6])